### ISSUE TITLE
Support for multiple GPUs

### ISSUE THREAD

**Issue by raynardj** [s14t284/TorchCRF#12]
This library does not support multiple gpu yet.

I know CRF is tiny in memory size, but it can always been used as the top layer on other larger models.

**Comment by raynardj** [comment]
I already tested the fix, the change won't be much. Please allow the writer access :-)

**Comment by rikeda71** [comment]
@raynardj 
Thank you for the issue.
If you don't mind, you can fix its and make pull requests ?

**Comment by raynardj** [comment]
> @raynardj
> Thank you for the issue.
> If you don't mind, you can fix its and make pull requests ?
Sure, I've already created a local branch and tested the fix, will push the local branch(currently denied, needs write access) and make pull request afterwards.

**Comment by rikeda71** [comment]
@raynardj 
Please refer to the procedure below to make pull request ?
https://jarednielsen.com/learn-git-fork-pull-request/

1. Fork this repository
2. Checkout branch
3. Edit codes
4. Commit and push to your forked repository
5. Make pull request from your forked repository

This steps does not require authority of writable access
