### ISSUE TITLE
How can I use TorchCRF with huggingface transformers?

### ISSUE THREAD

**Issue by hasansalimkanmaz** [s14t284/TorchCRF#16]
When I try to implement this package on top of a bert model, I got an 'IndexError' due to padding token id.I think this is caused by subtokens in an entity that have -100 value by default. Should I eliminate subtokens for crf layer, If so how can I do it?

**Comment by rikeda71** [comment]
Is [this code](https://github.com/dsindex/ntagger/blob/aa57f358945de1a2fb9d95808efac06a8d3d20c4/model.py#L422-L593) helpful for your question?

This library is inspired by the `pytorch-crf` used here.
If that doesn't work, could you show me your code?

**Comment by hasansalimkanmaz** [comment]
I think that their implementation may be wrong. Because I see that they are not filtering subtokens. This can mislead crf layer. Btw, crf layer can see every possibility of transitions and this is against its core idea. I will create another issue where you pointed out the code.

Thanks for your answer.
